---
# tasks file for jenkins

- name: Creating user jenkins
  become: yes
  user:
    name: jenkins
    password: $1$xxx$tGkhOO/GhZ9iP0mC8uwZi.

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s

- name: Add jenkins user to wheel group
  become: yes
  user:
    name: jenkins
    groups: wheel
    append: yes

#java -Duser.home=/opt/jenkins -Xms1000m -Xmx1200m -jar /<path>/jenkins.war

#openssl passwd -salt <salt> -1 <plaintext>
